In [1]:
import os
import glob
import pandas as pd
import pickle
import matplotlib.pyplot as plt
import numpy as np
import random
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import pprint
import pyspark
import pyspark.sql.functions as F

from pyspark.sql.functions import col
from pyspark.sql.types import StringType, IntegerType, FloatType, DateType

from sklearn.model_selection import train_test_split, StratifiedKFold,GroupShuffleSplit
from sklearn.preprocessing import StandardScaler,OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

import xgboost as xgb
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import make_scorer, f1_score, roc_auc_score
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

## set up pyspark session

In [26]:
# Initialize SparkSession
spark = pyspark.sql.SparkSession.builder \
    .appName("dev") \
    .master("local[*]") \
    .getOrCreate()

# Set log level to ERROR to hide warnings
spark.sparkContext.setLogLevel("ERROR")

## set up config

In [27]:
# set up config
model_train_date_str = "2024-09-01"
train_test_period_months = 12
oot_period_months = 2
train_test_ratio = 0.8

config = {}
config["model_train_date_str"] = model_train_date_str
config["train_test_period_months"] = train_test_period_months
config["oot_period_months"] =  oot_period_months
config["model_train_date"] =  datetime.strptime(model_train_date_str, "%Y-%m-%d")
config["oot_end_date"] =  config['model_train_date'] - timedelta(days = 1)
config["oot_start_date"] =  config['model_train_date'] - relativedelta(months = oot_period_months)
config["train_test_end_date"] =  config["oot_start_date"] - timedelta(days = 1)
config["train_test_start_date"] =  config["oot_start_date"] - relativedelta(months = train_test_period_months)
config["train_test_ratio"] = train_test_ratio 


pprint.pprint(config)

{'model_train_date': datetime.datetime(2024, 9, 1, 0, 0),
 'model_train_date_str': '2024-09-01',
 'oot_end_date': datetime.datetime(2024, 8, 31, 0, 0),
 'oot_period_months': 2,
 'oot_start_date': datetime.datetime(2024, 7, 1, 0, 0),
 'train_test_end_date': datetime.datetime(2024, 6, 30, 0, 0),
 'train_test_period_months': 12,
 'train_test_ratio': 0.8,
 'train_test_start_date': datetime.datetime(2023, 7, 1, 0, 0)}

## get label store

In [28]:
# connect to label store
folder_path = "datamart/gold/label_store/"
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
label_store_sdf = spark.read.option("header", "true").parquet(*files_list)
print("row_count:",label_store_sdf.count())

label_store_sdf.show()

row_count: 8974
+--------------------+-----------+-----+----------+-------------+
|             loan_id|Customer_ID|label| label_def|snapshot_date|
+--------------------+-----------+-----+----------+-------------+
|CUS_0x1037_2023_0...| CUS_0x1037|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1069_2023_0...| CUS_0x1069|    0|30dpd_6mob|   2023-07-01|
|CUS_0x114a_2023_0...| CUS_0x114a|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1184_2023_0...| CUS_0x1184|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1297_2023_0...| CUS_0x1297|    1|30dpd_6mob|   2023-07-01|
|CUS_0x12fb_2023_0...| CUS_0x12fb|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1325_2023_0...| CUS_0x1325|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1341_2023_0...| CUS_0x1341|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1375_2023_0...| CUS_0x1375|    1|30dpd_6mob|   2023-07-01|
|CUS_0x13a8_2023_0...| CUS_0x13a8|    0|30dpd_6mob|   2023-07-01|
|CUS_0x13ef_2023_0...| CUS_0x13ef|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1440_2023_0...| CUS_0x1440|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1443_2023_0...| CUS_0x1443|    0|30dpd_6mob|   2023-07-01|
|CUS_0x145a_2023_0...| CUS_0x145a|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1492_2023_0...| CUS_0x1492|    0|30dpd_6mob|   2023-07-01|
|CUS_0x153d_2023_0...| CUS_0x153d|    0|30dpd_6mob|   2023-07-01|
|CUS_0x1567_2023_0...| CUS_0x1567|    0|30dpd_6mob|   2023-07-01|
|CUS_0x15ad_2023_0...| CUS_0x15ad|    1|30dpd_6mob|   2023-07-01|
|CUS_0x1630_2023_0...| CUS_0x1630|    1|30dpd_6mob|   2023-07-01|
|CUS_0x169c_2023_0...| CUS_0x169c|    0|30dpd_6mob|   2023-07-01|
+--------------------+-----------+-----+----------+-------------+
only showing top 20 rows

In [29]:
# extract label store
labels_sdf = label_store_sdf.filter((col("snapshot_date") >= config["train_test_start_date"]) & (col("snapshot_date") <= config["oot_end_date"]))

print("extracted labels_sdf", labels_sdf.count(), config["train_test_start_date"], config["oot_end_date"])

extracted labels_sdf 6961 2023-07-01 00:00:00 2024-08-31 00:00:00

## get features

In [30]:
# connect to feature store
folder_path = "datamart/gold/feature_store/"
files_list = [folder_path+os.path.basename(f) for f in glob.glob(os.path.join(folder_path, '*'))]
features_store_sdf = spark.read.option("header", "true").parquet(*files_list)
print("row_count:",features_store_sdf.count())

features_store_sdf.show()

row_count: 11974
+-----------+--------------------+---------------+------+--------+-------------------------+-------------+-------------+---------------------+-----------------+---------------+-------------+-----------+--------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+-------------------+-----------------------+--------------------+---------------+-------------------------+---+-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+---------------------------+-------------------+--------------------+--------------------------+-----------------------+--------------------+--------------+-------------------+-----------------------+-------------------+----------------------------+--------+----------------+----------------+-----------------------+
|Customer_ID|             loan_id|loan_start_date|tenure|loan_amt|Scheduled_Installment_Amt|snapshot_date|Annual_Income|Monthly_Inhand_Salary|Num_Bank_Accounts|Num_Credit_Card|Interest_Rate|Num_of_Loan|        Type_of_Loan|Delay_from_due_date|Num_of_Delayed_Payment|Changed_Credit_Limit|Num_Credit_Inquiries|Credit_Mix|Outstanding_Debt|Credit_Utilization_Ratio|Payment_of_Min_Amount|Total_EMI_per_month|Amount_invested_monthly|   Payment_Behaviour|Monthly_Balance|Credit_History_Age_Months|Age|   Occupation|  fe_1|  fe_2|  fe_3|  fe_4|  fe_5|  fe_6|  fe_7|  fe_8|  fe_9| fe_10| fe_11| fe_12| fe_13| fe_14| fe_15| fe_16| fe_17| fe_18| fe_19| fe_20|Clickstream_Months_Observed|EMI_to_Income_Ratio|Debt_to_Income_Ratio|Investment_to_Income_Ratio|Balance_to_Income_Ratio|Delayed_Payment_Rate|Post_EMI_Slack|Loan_Type_Diversity|Credit_Utilization_Band|Credit_History_Band|Recent_Credit_Expansion_Flag|Age_Band|Occupation_Group|Clickstream_Mean|Clickstream_Vector_Norm|
+-----------+--------------------+---------------+------+--------+-------------------------+-------------+-------------+---------------------+-----------------+---------------+-------------+-----------+--------------------+-------------------+----------------------+--------------------+--------------------+----------+----------------+------------------------+---------------------+-------------------+-----------------------+--------------------+---------------+-------------------------+---+-------------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+------+---------------------------+-------------------+--------------------+--------------------------+-----------------------+--------------------+--------------+-------------------+-----------------------+-------------------+----------------------------+--------+----------------+----------------+-----------------------+
| CUS_0x1048|CUS_0x1048_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     42387.54|               3680.3|                3|              7|           26|          7|Personal Loan, No...|                  9|                     8|               10.34|                 7.0|  Standard|         1835.67|                   28.75|                  Yes|             225.88|                 133.51|High_spent_Small_...|         268.63|                      120| 27|   Accountant|113.07|110.93| 136.5| 94.57|118.79|108.43| 67.57| 88.86|139.21| 76.79|103.07|123.14| 116.0|  82.0| 87.43|101.14| 77.14|105.36| 90.29|111.29|                         14|             0.0614|              0.0433|                    0.0363|                  0.073|              1.1429|       3454.42|                  5|                    Low|        Established|                           1|  25to39|    Professional|          102.58|                 466.58|
| CUS_0x10c0|CUS_0x10c0_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     49454.13|              4328.18|                8|              5|           23|          2|Payday Loan, and ...|                 59|                    23|                4.95|                 8.0|       Bad|         1388.56|                   28.98|                 NULL|              73.35|                 148.54|Low_spent_Medium_...|         459.08|                      160| 39|    Architect|126.57| 111.5|103.43|132.57|118.93| 98.29|109.07| 74.64| 57.79| 69.79|156.14|118.21|  74.0| 94.36| 84.29| 44.14| 29.71|144.71| 89.29|  89.0|                         14|             0.0169|              0.0281|                    0.0343|                 0.1061|                11.5|       4254.83|                  2|                    Low|        Established|                           1|  25to39|    Professional|           96.32|                 453.55|
| CUS_0x115c|CUS_0x115c_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     41695.76|              3401.65|                6|              7|           15|          9|Not Specified, Cr...|                 24|                    20|               31.99|                 8.0|       Bad|         4453.51|                    26.7|                 NULL|             302.81|                  85.68|Low_spent_Large_v...|         221.67|                      102| 20|     Engineer| 90.21| 86.14| 52.57| 68.86|166.14| 95.57| 73.71|  78.0|131.71|161.36| 81.64| 75.93|148.36| 80.36|108.07| 99.36| 105.0|113.36|  99.0|134.57|                         14|              0.089|              0.1068|                    0.0252|                 0.0652|              2.2222|       3098.84|                  5|                    Low|        Established|                           1| Under25|    Professional|           102.5|                 478.47|
| CUS_0x12b6|CUS_0x12b6_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     67104.12|              5829.01|                9|              9|           19|          5|Student Loan, Not...|                 28|                    25|               21.54|                 8.0|       Bad|         4635.75|                   27.64|                  Yes|             265.02|                   NULL|Low_spent_Medium_...|         391.62|                       21| 18|       Writer| 91.86| 96.14|110.57|  82.5| 106.5|125.86|134.57| 132.5|142.07|195.57| 57.64|121.36| 78.29|105.93|109.86|118.64| 73.43| 92.57|113.71| 126.5|                         14|             0.0455|              0.0691|                      NULL|                 0.0672|                 5.0|       5563.99|                  4|                    Low|                New|                           1| Under25|        Creative|           110.8|                 512.28|
| CUS_0x12b8|CUS_0x12b8_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|      15906.4|              1350.53|                9|             10|           21|          8|Credit-Builder Lo...|                 22|                    21|               27.86|                 6.0|       Bad|         3167.74|                   31.09|                  Yes|              91.89|                 119.61|Low_spent_Small_v...|         213.55|                      131| 29|       Doctor|108.21|117.71| 84.21|104.64|128.64|  98.0| 87.07|129.86|102.14|  92.0|  83.5| 92.43| 41.14|117.86|109.79| 92.29| 28.21|106.57|  80.5|  52.5|                         14|              0.068|              0.1991|                    0.0886|                 0.1581|               2.625|       1258.64|                  5|                 Medium|        Established|                           1|  25to39|    Professional|           92.86|                 431.46|
| CUS_0x12ef|CUS_0x12ef_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|      68898.0|               5588.5|                7|              4|           11|          0|             No Loan|                 24|                    16|                 5.8|                 5.0|  Standard|          312.14|                   29.86|                   No|                0.0|                 195.79|                NULL|         613.06|                      338| 43|     Mechanic| 90.64| 111.5|124.79| 73.86|101.79| 86.21| 77.64|114.07|126.29|159.71|145.29| 84.71| 64.93| 96.07| 91.64|157.57| 83.29| 85.71|118.36| 81.43|                         14|                0.0|              0.0045|                     0.035|                 0.1097|                NULL|        5588.5|                  0|                    Low|        Long_Tenure|                           1|  40to59|           Trade|          103.78|                 479.42|
| CUS_0x134d|CUS_0x134d_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     85324.44|              7286.37|                5|              7|           18|          3|Auto Loan, Person...|                 12|                    12|               16.22|                 7.0|  Standard|          713.09|                   28.65|                  Yes|             197.31|                 279.82|High_spent_Medium...|         501.51|                      342| 43|Media_Manager| 82.71|  90.0| 83.14|110.57|147.14|124.36|115.36|116.29| 97.93|121.64|105.21|119.64| 113.0|103.71| 56.14|107.43|104.07| 84.07| 67.43|124.79|                         14|             0.0271|              0.0084|                    0.0384|                 0.0688|                 4.0|       7089.06|                  3|                    Low|        Long_Tenure|                           1|  40to59|        Creative|          103.73|                 473.32|
| CUS_0x13c2|CUS_0x13c2_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     60682.11|              5179.84|                8|              5|           23|          5|Home Equity Loan,...|                 41|                    18|               26.12|                 9.0|       Bad|         4899.87|                   35.25|                  Yes|             195.45|                 142.66|Low_spent_Medium_...|         386.53|                      113| 40|      Teacher|128.64| 70.36|135.29| 95.79|118.36|135.71| 80.43| 16.07|  81.0|134.79| 84.14| 91.36|118.57| 75.21| 83.93|119.43|113.57|156.14|107.93|103.57|                         14|             0.0377|              0.0807|                    0.0275|                 0.0746|                 3.6|       4984.39|                  4|                 Medium|        Established|                           1|  40to59|       Education|          102.51|                  478.5|
| CUS_0x1414|CUS_0x1414_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     51093.12|              4080.76|                8|              9|           25|          6|Credit-Builder Lo...|                 42|                    22|               27.67|                12.0|       Bad|          3628.5|                   30.71|                  Yes|             246.09|                 330.92|Low_spent_Small_v...|         121.07|                      134| 46|   Journalist|103.71| 80.36|110.71|114.43|148.14|124.21| 71.07| 85.71|126.57|149.29| 95.07|103.07|122.14| 91.57|113.14| 88.79|136.07| 107.0|124.43| 79.14|                         14|             0.0603|               0.071|                    0.0811|                 0.0297|              3.6667|       3834.67|                  4|                 Medium|        Established|                           1|  40to59|        Creative|          108.73|                 495.99|
| CUS_0x1470|CUS_0x1470_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     14156.88|              1251.74|                3|              4|            4|          4|Mortgage Loan, No...|                  0|                     8|                8.86|                 4.0|      Good|           602.3|                   31.11|                   No|               NULL|                  91.45|Low_spent_Small_v...|         287.06|                      324| 24|   Accountant|111.93| 56.71|101.86|122.29| 89.36|111.93|132.14|126.71| 87.36|  72.5|129.43| 95.21| 88.79|106.71| 94.79|  83.5|113.14|119.07| 110.0| 84.71|                         14|               NULL|              0.0425|                    0.0731|                 0.2293|                 2.0|          NULL|                  4|                 Medium|        Long_Tenure|                           1| Under25|    Professional|          101.91|                  464.0|
| CUS_0x15cc|CUS_0x15cc_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|      9669.05|               925.75|                8|              6|           31|          6|Credit-Builder Lo...|                 27|                    23|               -4.75|                15.0|       Bad|         1626.12|                   32.38|                  Yes|              44.19|                  49.24|Low_spent_Small_v...|         289.15|                      118| 25|      Manager| 76.57| 79.64|101.43|121.64|110.07| 130.5|167.64|  75.5|143.86| 95.14|  82.0|111.57| 98.07| 77.07|117.86| 93.29|133.21| 62.21| 81.64|104.79|                         14|             0.0477|              0.1682|                    0.0532|                 0.3123|              3.8333|        881.56|                  5|                 Medium|        Established|                           0|  25to39|        Business|          103.18|                 475.99|
| CUS_0x15da|CUS_0x15da_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|    127014.28|             10870.52|                7|              6|           14|          3|Payday Loan, Stud...|                 28|                    13|                NULL|                 9.0|      NULL|          245.63|                   36.14|                  Yes|             215.38|                 323.43|Low_spent_Medium_...|         828.24|                      109| 24|       Doctor| 44.71|109.36|106.79|  55.5| 102.0|138.21|111.93|  94.0|138.93|105.93|106.21|104.93| 91.93| 82.29|122.29|128.29|114.36|  67.0|113.64|123.43|                         14|             0.0198|              0.0019|                    0.0298|                 0.0762|              4.3333|      10655.14|                  3|                 Medium|        Established|                           0| Under25|    Professional|          103.09|                 473.79|
| CUS_0x15f7|CUS_0x15f7_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     60314.22|              5004.19|               10|              7|           16|          7|Debt Consolidatio...|                 43|                    13|                9.32|                14.0|  Standard|         1902.05|                   26.78|                  Yes|             219.98|                 142.26|High_spent_Medium...|         388.18|                      209| 19|     Engineer| 38.79| 48.14|142.79|108.43|141.43|112.36| 83.79| 41.79| 78.36| 97.14|127.86| 98.79|107.07| 63.21| 101.0| 76.14| 82.64|101.86| 89.93|131.64|                         14|              0.044|              0.0315|                    0.0284|                 0.0776|              1.8571|       4784.21|                  5|                    Low|        Long_Tenure|                           1| Under25|    Professional|           93.66|                 439.46|
| CUS_0x1739|CUS_0x1739_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     14144.48|              1206.71|                7|              9|           16|          6|Auto Loan, Payday...|                 25|                    18|                4.93|                17.0|       Bad|         2537.18|                   29.75|                  Yes|              47.61|                 136.66|Low_spent_Small_v...|         321.27|                      141| 42|    Scientist| 53.29|102.71|106.64| 75.07|105.36| 98.71| 83.86|104.36| 90.07| 89.29|170.79| 94.21|143.71| 22.36| 85.79| 46.86| 79.07| 50.07|115.43|106.14|                         14|             0.0395|              0.1794|                    0.1133|                 0.2662|                 3.0|        1159.1|                  4|                    Low|        Established|                           1|  40to59|    Professional|           91.19|                 432.84|
| CUS_0x178b|CUS_0x178b_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|      43456.5|              3437.38|                2|           NULL|            8|          0|             No Loan|               NULL|                     8|                0.62|                 3.0|      NULL|           389.9|                    24.3|                 NULL|                0.0|                 398.75|Low_spent_Small_v...|         234.99|                      377| 45|    Developer| 89.21|104.71| 84.14| 94.79| 98.21| 81.07| 56.43|117.21|125.64| 140.5| 84.14| 92.79|124.07|102.79|122.07| 87.86| 91.57|102.29| 107.0|  75.0|                         14|                0.0|               0.009|                     0.116|                 0.0684|                NULL|       3437.38|                  0|                    Low|        Long_Tenure|                           1|  40to59|    Professional|           99.07|                 451.49|
| CUS_0x17ec|CUS_0x17ec_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     30813.68|              2109.21|                3|              3|            8|          4|Auto Loan, Studen...|                  7|                    10|                6.93|                 2.0|      NULL|          1312.2|                   35.38|                   No|             236.66|                 198.93|Low_spent_Large_v...|          244.0|                      226| 39|    Architect|104.07| 83.93|108.29|115.71|112.64| 68.86|105.71|148.43|126.36|181.93| 97.71| 82.29|110.14|121.86|  69.0| 72.79| 65.14| 85.86|124.21|125.71|                         14|             0.1122|              0.0426|                    0.0943|                 0.1157|                 2.5|       1872.55|                  3|                 Medium|        Long_Tenure|                           1|  25to39|    Professional|          105.53|                 488.77|
| CUS_0x18f4|CUS_0x18f4_2024_0...|     2024-02-01|    10| 10000.0|                      0.0|   2024-02-01|     35805.25|              3106.77|                4|              7|           16|          0|             No Loan|                 24|                    15|                3.81|                 2.0|  Standard|          723.27|                   37.08|                   No|                0.0|                  99.91|High_spent_Medium...|         460.77|                      303| 23|      Teacher| 82.64| 98.71| 85.07|124.64|142.14| 65.43| 94.57|131.14| 91.57| 97.43| 142.5|125.64| 101.0|133.79|116.36|120.43| 94.79| 83.79| 98.57| 73.07|                         14|                0.0|              0.0202|                    0.0322|                 0.1483|                NULL|       3106.77|                  0|                 Medium|        Long_Tenure|                           1| Under25|       Education|          105.16|                 480.78|

In [31]:
# extract features from feature store
features_sdf = features_store_sdf.filter((col("snapshot_date") >= config["train_test_start_date"]) & (col("snapshot_date") <= config["oot_end_date"]))

print("extracted features_sdf", features_sdf.count(), config["train_test_start_date"], config["oot_end_date"])

extracted features_sdf 6937 2023-07-01 00:00:00 2024-08-31 00:00:00

## prepare data for modeling

In [32]:
feat = (features_store_sdf
        .withColumnRenamed("snapshot_date", "feature_snapshot_date")
        .drop("Customer_ID"))

data_pdf = labels_sdf.join(feat, on="loan_id", how="left").toPandas()

In [39]:
data_pdf

,loan_id,Customer_ID,label,label_def,snapshot_date,loan_start_date,tenure,loan_amt,Scheduled_Installment_Amt,feature_snapshot_date,...,Delayed_Payment_Rate,Post_EMI_Slack,Loan_Type_Diversity,Credit_Utilization_Band,Credit_History_Band,Recent_Credit_Expansion_Flag,Age_Band,Occupation_Group,Clickstream_Mean,Clickstream_Vector_Norm
0,CUS_0x1037_2023_01_01,CUS_0x1037,0,30dpd_6mob,2023-07-01,2023-01-01,10,10000.0,0.0,2023-01-01,...,3.7500,1052.62,3,High,Long_Tenure,1,40to59,Professional,55.90,462.96
1,CUS_0x1069_2023_01_01,CUS_0x1069,0,30dpd_6mob,2023-07-01,2023-01-01,10,10000.0,0.0,2023-01-01,...,NaN,4659.56,3,Low,Long_Tenure,1,25to39,Professional,81.25,605.00
2,CUS_0x114a_2023_01_01,CUS_0x114a,0,30dpd_6mob,2023-07-01,2023-01-01,10,10000.0,0.0,2023-01-01,...,1.0000,1210.16,2,Low,Long_Tenure,1,40to59,Professional,108.35,723.95
3,CUS_0x1184_2023_01_01,CUS_0x1184,0,30dpd_6mob,2023-07-01,2023-01-01,10,10000.0,0.0,2023-01-01,...,3.0000,1354.01,3,Low,Long_Tenure,1,40to59,Professional,105.40,576.99
4,CUS_0x1297_2023_01_01,CUS_0x1297,1,30dpd_6mob,2023-07-01,2023-01-01,10,10000.0,0.0,2023-01-01,...,2.6667,4585.23,6,Low,Established,1,40to59,Business,97.80,564.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6956,CUS_0xdf6_2023_09_01,CUS_0xdf6,0,30dpd_6mob,2024-03-01,2023-09-01,10,10000.0,0.0,2023-09-01,...,NaN,2449.47,0,Medium,Long_Tenure,1,40to59,Trade,107.67,509.71
6957,CUS_0xe23_2023_09_01,CUS_0xe23,0,30dpd_6mob,2024-03-01,2023-09-01,10,10000.0,0.0,2023-09-01,...,14.0000,1414.28,1,Medium,Long_Tenure,1,25to39,Creative,105.76,501.17
6958,CUS_0xe4e_2023_09_01,CUS_0xe4e,0,30dpd_6mob,2024-03-01,2023-09-01,10,10000.0,0.0,2023-09-01,...,NaN,8738.14,0,Medium,Long_Tenure,1,Under25,Professional,110.10,514.69
6959,CUS_0xedd_2023_09_01,CUS_0xedd,0,30dpd_6mob,2024-03-01,2023-09-01,10,10000.0,0.0,2023-09-01,...,3.2500,10107.61,4,Medium,Long_Tenure,0,40to59,Professional,111.34,519.29
6960,CUS_0xfe4_2023_09_01,CUS_0xfe4,0,30dpd_6mob,2024-03-01,2023-09-01,10,10000.0,0.0,2023-09-01,...,1.8571,8469.57,3,Medium,Long_Tenure,1,25to39,Creative,109.33,504.42

In [44]:
# split data into train - test - oot
oot_pdf = data_pdf[(data_pdf['snapshot_date'] >= config["oot_start_date"].date()) & (data_pdf['snapshot_date'] <= config["oot_end_date"].date())]
train_test_pdf = data_pdf[(data_pdf['snapshot_date'] >= config["train_test_start_date"].date()) & (data_pdf['snapshot_date'] <= config["train_test_end_date"].date())]

exclude = ['loan_id', 'snapshot_date', 'label', 'feature_snapshot_date', 'Customer_ID',
           'label_def', 'loan_start_date', 'Occupation', 'Type_of_Loan']
feature_cols = [c for c in data_pdf.columns if c not in exclude]
cat_cols = [c for c in feature_cols if data_pdf[c].dtype == "object"]
num_cols = [c for c in feature_cols if c not in cat_cols]

X_oot = oot_pdf[feature_cols]
y_oot = oot_pdf["label"]
X_train, X_test, y_train, y_test = train_test_split(
    train_test_pdf[feature_cols], train_test_pdf["label"], 
    test_size= 1 - config["train_test_ratio"],
    random_state=88,     # Ensures reproducibility
    shuffle=True,        # Shuffle the data before splitting
    stratify=train_test_pdf["label"]           # Stratify based on the label column
)


print('X_train', X_train.shape[0])
print('X_test', X_test.shape[0])
print('X_oot', X_oot.shape[0])
print('y_train', y_train.shape[0], round(y_train.mean(),2))
print('y_test', y_test.shape[0], round(y_test.mean(),2))
print('y_oot', y_oot.shape[0], round(y_oot.mean(),2))

X_train

X_train 4766
X_test 1192
X_oot 1003
y_train 4766 0.28
y_test 1192 0.28
y_oot 1003 0.29

,tenure,loan_amt,Scheduled_Installment_Amt,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,...,Delayed_Payment_Rate,Post_EMI_Slack,Loan_Type_Diversity,Credit_Utilization_Band,Credit_History_Band,Recent_Credit_Expansion_Flag,Age_Band,Occupation_Group,Clickstream_Mean,Clickstream_Vector_Norm
137,10,10000.0,0.0,48783.44,4187.29,3.0,7.0,18.0,3.0,11.0,...,5.3333,4107.67,3,Low,Long_Tenure,1,Under25,Unknown,96.05,657.80
4090,10,10000.0,0.0,78999.96,6396.33,8.0,5.0,20.0,4.0,42.0,...,6.7500,6258.07,3,Medium,Established,1,40to59,Trade,116.94,537.85
3489,10,10000.0,0.0,15026.04,1059.17,10.0,5.0,28.0,6.0,19.0,...,2.8333,1019.69,5,Medium,Established,1,25to39,Trade,128.30,667.12
431,10,10000.0,0.0,89122.80,7141.90,7.0,3.0,12.0,1.0,31.0,...,14.0000,7084.14,1,Medium,Long_Tenure,1,40to59,Creative,105.85,624.46
4120,10,10000.0,0.0,16753.63,1564.14,6.0,9.0,23.0,9.0,37.0,...,2.7778,1478.58,5,Medium,Established,1,Under25,Professional,94.64,443.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2211,10,10000.0,0.0,14489.93,1151.49,3.0,3.0,18.0,1.0,26.0,...,12.0000,1141.86,1,Medium,Long_Tenure,1,25to39,Creative,92.06,474.89
4145,10,10000.0,0.0,156687.16,13095.26,2.0,3.0,7.0,1.0,0.0,...,5.0000,13014.68,1,High,Long_Tenure,0,25to39,Business,113.72,537.79
2304,10,10000.0,0.0,133670.48,11076.21,3.0,3.0,20.0,4.0,13.0,...,2.2500,10812.63,3,Medium,Long_Tenure,1,40to59,Professional,96.69,471.82
6398,10,10000.0,0.0,17585.29,1571.44,7.0,7.0,33.0,5.0,28.0,...,2.0000,1526.66,3,Low,Established,1,Under25,Professional,97.69,472.24
6095,10,10000.0,0.0,30910.68,2066.93,6.0,3.0,17.0,3.0,25.0,...,6.6667,1703.96,3,Medium,Established,1,25to39,Creative,95.20,454.39

In [45]:
cat_cols

['Credit_Mix',
 'Payment_of_Min_Amount',
 'Payment_Behaviour',
 'Credit_Utilization_Band',
 'Credit_History_Band',
 'Age_Band',
 'Occupation_Group']

## preprocess data

In [49]:
preprocessor = ColumnTransformer([
    ("num", StandardScaler(), num_cols),
    ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), cat_cols),
])

# fit on train only; test and OOT are transformed with train statistics
transformer_stdscaler = preprocessor.fit(X_train)

X_train_processed = transformer_stdscaler.transform(X_train)
X_test_processed  = transformer_stdscaler.transform(X_test)
X_oot_processed   = transformer_stdscaler.transform(X_oot)

print('X_train_processed', X_train_processed.shape)
print('X_test_processed', X_test_processed.shape)
print('X_oot_processed', X_oot_processed.shape)

pd.DataFrame(X_train_processed, columns=transformer_stdscaler.get_feature_names_out())

X_train_processed (4766, 81)
X_test_processed (1192, 81)
X_oot_processed (1003, 81)

,num__tenure,num__loan_amt,num__Scheduled_Installment_Amt,num__Annual_Income,num__Monthly_Inhand_Salary,num__Num_Bank_Accounts,num__Num_Credit_Card,num__Interest_Rate,num__Num_of_Loan,num__Delay_from_due_date,...,cat__Age_Band_25to39,cat__Age_Band_40to59,cat__Age_Band_60plus,cat__Age_Band_Under25,cat__Occupation_Group_Business,cat__Occupation_Group_Creative,cat__Occupation_Group_Education,cat__Occupation_Group_Professional,cat__Occupation_Group_Trade,cat__Occupation_Group_Unknown
0,0.0,0.0,0.0,-0.039359,0.007524,-0.923253,0.736479,0.401850,-0.206565,-0.680640,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.758436,0.711366,1.020220,-0.239387,0.629550,0.200584,1.406006,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,-0.930644,-0.989154,1.797609,-0.239387,1.540349,1.014881,-0.142150,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.025706,0.948919,0.631525,-1.215254,-0.281249,-1.020862,0.665583,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,-0.885031,-0.828261,0.242831,1.712346,0.971100,2.236328,1.069450,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4761,0.0,0.0,0.0,-0.944799,-0.959739,-0.923253,-1.215254,0.401850,-1.020862,0.329028,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4762,0.0,0.0,0.0,2.809584,2.845772,-1.311947,-1.215254,-0.850498,-1.020862,-1.421062,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4763,0.0,0.0,0.0,2.201882,2.202465,-0.923253,-1.215254,0.629550,0.200584,-0.546017,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4764,0.0,0.0,0.0,-0.863073,-0.825935,0.631525,0.736479,2.109598,0.607733,0.463650,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4765,0.0,0.0,0.0,-0.511247,-0.668062,0.242831,-1.215254,0.288000,-0.206565,0.261717,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

## train model

In [50]:
# Define the XGBoost classifier
xgb_clf = xgb.XGBClassifier(eval_metric='logloss', random_state=88)

cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=88)

# Define the hyperparameter space to search
param_dist = {
    'n_estimators': [25, 50],
    'max_depth': [2, 3],  # lower max_depth to simplify the model
    'learning_rate': [0.01, 0.1],
    'subsample': [0.6, 0.8],
    'colsample_bytree': [0.6, 0.8],
    'gamma': [0, 0.1],
    'min_child_weight': [1, 3, 5],
    'reg_alpha': [0, 0.1, 1],
    'reg_lambda': [1, 1.5, 2]
}

# Create a scorer based on AUC score
auc_scorer = make_scorer(roc_auc_score)

# Set up the random search with cross-validation
random_search = RandomizedSearchCV(
    estimator=xgb_clf,
    param_distributions=param_dist,
    scoring=auc_scorer,
    n_iter=10,  # Number of iterations for random search
    cv=3,       # Number of folds in cross-validation
    verbose=1,
    random_state=42,
    n_jobs=-1   # Use all available cores
)

# Perform the random search
random_search.fit(X_train_processed, y_train)

# Output the best parameters and best score
print("Best parameters found: ", random_search.best_params_)
print("Best AUC score: ", random_search.best_score_)

# Evaluate the model on the train set
best_model = random_search.best_estimator_
y_pred_proba = best_model.predict_proba(X_train_processed)[:, 1]
train_auc_score = roc_auc_score(y_train, y_pred_proba)
print("Train AUC score: ", train_auc_score)

# Evaluate the model on the test set
best_model = random_search.best_estimator_
y_pred_proba = best_model.predict_proba(X_test_processed)[:, 1]
test_auc_score = roc_auc_score(y_test, y_pred_proba)
print("Test AUC score: ", test_auc_score)

# Evaluate the model on the oot set
best_model = random_search.best_estimator_
y_pred_proba = best_model.predict_proba(X_oot_processed)[:, 1]
oot_auc_score = roc_auc_score(y_oot, y_pred_proba)
print("OOT AUC score: ", oot_auc_score)

print("TRAIN GINI score: ", round(2*train_auc_score-1,3))
print("Test GINI score: ", round(2*test_auc_score-1,3))
print("OOT GINI score: ", round(2*oot_auc_score-1,3))

Fitting 3 folds for each of 10 candidates, totalling 30 fits
Best parameters found:  {'subsample': 0.6, 'reg_lambda': 1, 'reg_alpha': 0, 'n_estimators': 50, 'min_child_weight': 1, 'max_depth': 3, 'learning_rate': 0.1, 'gamma': 0.1, 'colsample_bytree': 0.8}
Best AUC score:  0.7379415027284354
Train AUC score:  0.9020809700245122
Test AUC score:  0.8795009283842644
OOT AUC score:  0.9132398934321788
TRAIN GINI score:  0.804
Test GINI score:  0.759
OOT GINI score:  0.826

## prepare model artefact to save

In [51]:
model_artefact = {}

model_artefact['model'] = best_model
model_artefact['model_version'] = "credit_model_"+config["model_train_date_str"].replace('-','_')
model_artefact['preprocessing_transformers'] = {}
model_artefact['preprocessing_transformers']['stdscaler'] = transformer_stdscaler
model_artefact['data_dates'] = config
model_artefact['data_stats'] = {}
model_artefact['data_stats']['X_train'] = X_train.shape[0]
model_artefact['data_stats']['X_test'] = X_test.shape[0]
model_artefact['data_stats']['X_oot'] = X_oot.shape[0]
model_artefact['data_stats']['y_train'] = round(y_train.mean(),2)
model_artefact['data_stats']['y_test'] = round(y_test.mean(),2)
model_artefact['data_stats']['y_oot'] = round(y_oot.mean(),2)
model_artefact['results'] = {}
model_artefact['results']['auc_train'] = train_auc_score
model_artefact['results']['auc_test'] = test_auc_score
model_artefact['results']['auc_oot'] = oot_auc_score
model_artefact['results']['gini_train'] = round(2*train_auc_score-1,3)
model_artefact['results']['gini_test'] = round(2*test_auc_score-1,3)
model_artefact['results']['gini_oot'] = round(2*oot_auc_score-1,3)
model_artefact['hp_params'] = random_search.best_params_


pprint.pprint(model_artefact)

{'data_dates': {'model_train_date': datetime.datetime(2024, 9, 1, 0, 0),
                'model_train_date_str': '2024-09-01',
                'oot_end_date': datetime.datetime(2024, 8, 31, 0, 0),
                'oot_period_months': 2,
                'oot_start_date': datetime.datetime(2024, 7, 1, 0, 0),
                'train_test_end_date': datetime.datetime(2024, 6, 30, 0, 0),
                'train_test_period_months': 12,
                'train_test_ratio': 0.8,
                'train_test_start_date': datetime.datetime(2023, 7, 1, 0, 0)},
 'data_stats': {'X_oot': 1003,
                'X_test': 1192,
                'X_train': 4766,
                'y_oot': np.float64(0.29),
                'y_test': np.float64(0.28),
                'y_train': np.float64(0.28)},
 'hp_params': {'colsample_bytree': 0.8,
               'gamma': 0.1,
               'learning_rate': 0.1,
               'max_depth': 3,
               'min_child_weight': 1,
               'n_estimators': 50,
               'reg_alpha': 0,
               'reg_lambda': 1,
               'subsample': 0.6},
 'model': XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=0.1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=50, n_jobs=None,
              num_parallel_tree=None, ...),
 'model_version': 'credit_model_2024_09_01',
 'preprocessing_transformers': {'stdscaler': ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['tenure', 'loan_amt',
                                  'Scheduled_Installment_Amt', 'Annual_Income',
                                  'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
                                  'Num_Credit_Card', 'Interest_Rate',
                                  'Num_of_Loan', 'Delay_from_due_date',
                                  'Num_of_Delayed_Payment',
                                  'Changed_Credit_Limit',
                                  'Num_Credit_Inquiries', 'Outstanding_Debt',
                                  'Credit_Utilization_Ratio...
                                  'Amount_invested_monthly', 'Monthly_Balance',
                                  'Credit_History_Age_Months', 'Age', 'fe_1',
                                  'fe_2', 'fe_3', 'fe_4', 'fe_5', 'fe_6',
                                  'fe_7', 'fe_8', 'fe_9', 'fe_10', ...]),
                                ('cat',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Credit_Mix', 'Payment_of_Min_Amount',
                                  'Payment_Behaviour',
                                  'Credit_Utilization_Band',
                                  'Credit_History_Band', 'Age_Band',
                                  'Occupation_Group'])])},
 'results': {'auc_oot': np.float64(0.9132398934321788),
             'auc_test': np.float64(0.8795009283842644),
             'auc_train': np.float64(0.9020809700245122),
             'gini_oot': np.float64(0.826),
             'gini_test': np.float64(0.759),
             'gini_train': np.float64(0.804)}}

## save artefact to model bank

In [52]:
# create model_bank dir
model_bank_directory = "model_bank/"

if not os.path.exists(model_bank_directory):
    os.makedirs(model_bank_directory)

In [53]:
# Full path to the file
file_path = os.path.join(model_bank_directory, model_artefact['model_version'] + '.pkl')

# Write the model to a pickle file
with open(file_path, 'wb') as file:
    pickle.dump(model_artefact, file)

print(f"Model saved to {file_path}")

Model saved to model_bank/credit_model_2024_09_01.pkl

## test load pickle and make model inference

In [54]:
# Load the model from the pickle file
with open(file_path, 'rb') as file:
    loaded_model_artefact = pickle.load(file)

y_pred_proba = loaded_model_artefact['model'].predict_proba(X_oot_processed)[:, 1]
oot_auc_score = roc_auc_score(y_oot, y_pred_proba)
print("OOT AUC score: ", oot_auc_score)

print("Model loaded successfully!")

OOT AUC score:  0.9132398934321788
Model loaded successfully!